# frozen_string_literal: true

source 'https://rubygems.org'

gem 'roda'
gem 'sequel'
gem 'sqlite3'
gem 'json'
gem 'rack'
gem 'rack-protection'
gem 'oauth2'
gem 'dotenv'
gem 'puma'
gem 'rack-cors'
gem 'ruby-openai'
gem 'openssl'

group :development, :test do
  gem 'rspec'
  gem 'pry'
  gem 'rubocop'
end

group :production do
  gem 'pg', '~>1.0'
end
