# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dotenv'
gem 'puma'
gem 'roda'
gem 'ruby-openai'
gem 'rake', '~>13.0'
gem 'sequel', '~>5.0'
gem 'dry-validation', '~>1.10'
gem 'rack-ssl-enforcer'
gem 'rbnacl'
gem 'rack-ssl-enforcer'

group :production do
  gem 'pg', '~>1.0'
end

group :development, :test do
  gem 'pry'
  gem 'sqlite3', '~> 1.0'
end

group :development do
  gem 'rubocop'
end