# Rakefile
require 'rake'
require 'sequel'
require 'dotenv/load'
require 'puma'
require 'puma/cli'

Dotenv.load

ENV['RACK_ENV'] ||= 'development'

DB_URL = case ENV['RACK_ENV']
when 'development'
  ENV['DATABASE_URL_DEV']
when 'test'
  ENV['DATABASE_URL_TEST']
else
  ENV['DATABASE_URL_PROD']
end

raise "Database URL is not set" unless DB_URL

namespace :db do
  desc 'Run migrations'
  task :migrate do
    Sequel.extension :migration
    DB = Sequel.connect(DB_URL)
    Sequel::Migrator.run(DB, 'db/migrations')
  end

  desc 'Create the database'
  task :create do
    case ENV['RACK_ENV']
    when 'development', 'test'
      FileUtils.mkdir_p('db')
    else
      system("createdb #{DB_URL.split('/').last}")
    end
  end

  desc 'Drop the database'
  task :drop do
    case ENV['RACK_ENV']
    when 'development', 'test'
      FileUtils.rm_f("db/#{ENV['RACK_ENV']}.sqlite3")
    else
      system("dropdb #{DB_URL.split('/').last}")
    end
  end
end

namespace :app do
  desc 'Run the application'
  task :run do
    require_relative 'config/routes'

    # Configure Puma to run with the defined configuration file
    Puma::CLI.new(['-C', 'config/puma.rb']).run
  end
end

task default: 'app:run'
